### ISSUE TITLE
Localhost:8080 remote access not possible

### ISSUE THREAD

**Issue by Sooriya10** [cockroachdb/cockroach-prod#85]
Cannot  access remotely . The server is an Ubuntu 

Quickstart 
step 5. Checkout the admin UI by pointing your browser to http://<localhost>:8080

Anyone can help?

**Comment by tschottdorf** [comment]
Please include more complete information on what you have done, have tried, and are trying to do.

**Comment by Sooriya10** [comment]
Install Cockroach DB.Start a local cluster with three nodes listening on different ports:$ ./cockroach start --insecure &
$ ./cockroach start --insecure --store=cockroach-data2 --port=26258 --http-port=8081 --join=localhost:26257 &
$ ./cockroach start --insecure --store=cockroach-data3 --port=26259 --http-port=8082 --join=localhost:26257 &Start the built-in SQL client as an interactive shell:$ ./cockroach sql --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.Run some CockroachDB SQL statements:root@:26257> CREATE DATABASE bank;
CREATE DATABASE

root@:26257> SET DATABASE = bank;
SET

root@:26257> CREATE TABLE accounts (id INT PRIMARY KEY, balance DECIMAL);
CREATE TABLE

root@26257> INSERT INTO accounts VALUES (1234, DECIMAL '10000.50');
INSERT 1

root@26257> SELECT * FROM accounts;
+------+----------+
|  id  | balance  |
+------+----------+
| 1234 | 10000.50 |
+------+----------+Checkout the admin UI by pointing your browser to http://<localhost>:8080.
Then tried to access via an URL, where my Ubuntu server IP was 13.92.137.50
 http://13.92.137.50:8080



Date: Fri, 15 Apr 2016 02:01:07 -0700

**Comment by tschottdorf** [comment]
The quickstart example sets up a cluster which listens only on localhost. Since you're trying to access the UI on an external address, you are probably interested in these instructions instead:

https://www.cockroachlabs.com/docs/manual-deployment.html

Note that they make use of the `--host` flag when starting the nodes.

**Comment by petermattis** [comment]
@tschottdorf Setting the `--host` flag should not be necessary since @Sooriya10 specified `--insecure`.

@Sooriya10 If I start a single-node cockroach cluster I see:

```
~/Development/go/src/github.com/cockroachdb/cockroach master ./cockroach start --insecure
build:     beta-20160407-204-g22203d5 @ 2016/04/15 13:36:27 (go1.6)
admin:     http://Peters-MacBook-Pro-2.local:8080
sql:       postgresql://root@Peters-MacBook-Pro-2.local:26257?sslmode=disable
logs:      cockroach-data/logs
store[0]:  path=cockroach-data
```

I'm able to see the admin UI by visiting `http://Peters-MacBook-Pro-2.local:8080`. I can also access the admin UI using my machine's IP address: `http://192.168.99.1:8080`. Can you try starting up a single node cluster using `./cockroach start --insecure` and providing the output that was displayed at startup.

**Comment by Sooriya10** [comment]
Yes, all it was needing --insecure   :)
Thanks guys!
running on http://40.112.142.253:8080/#/cluster

Date: Fri, 15 Apr 2016 06:41:36 -0700

**Comment by petermattis** [comment]
Sounds like this is resolved. Please reopen if I misunderstood.

**Comment by Sooriya10** [comment]
All good Peter! runnign@
www.nt8s.com
BTW: when this will be released as a version  1.0?
Date: Sat, 16 Apr 2016 07:41:54 -0700

**Comment by petermattis** [comment]
@Sooriya10 We're targeting the end of the year for a 1.0 release, though that date is not set in stone.

**Comment by Sooriya10** [comment]
Thanks for that info Peter! Hope I could involve with this product in some ways, but not sure how I could help in programming area tough..

Date: Sun, 17 Apr 2016 06:42:08 -0700
